- include_vars: "{{ ansible_os_family }}.yml"
- include_vars: "{{ ansible_service_mgr }}.yml"
- name: ensure that basic mailaliases have been configured
  lineinfile:
    dest: /etc/aliases
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
    line: '{{ item.user }}: {{ item.alias }}'
  with_items: "{{ mailaliases }}"
  notify:
    - build aliases.db
- name: ensure that postfix is installed
  package:
    name: "{{ postfix_package_name }}"
    state: present
- name: ensure that main.cf is present
  template:
    src: templates/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix
- name: ensure that sasl_passwd has been configured
  template:
    src: templates/sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  when: smtp_auth == true
  notify:
    - build sasl_passwd.db
- name: ensure that postfix service is running
  service:
    name: "{{ postfix_service_name }}"
    enabled: yes
    state: started
- name: ensure monit monitors postfix
  template:
    src: templates/postfix.monit.j2
    dest: /etc/monit/conf-enabled/postfix.monit
    owner: root
    group: root
    mode: 0644
  notify:
    - restart monit
  when: postfix_manage_monit == true
