- name: restart postfix
  service:
    name: "{{ postfix_service_name }}"
    state: restarted
- name: build sasl_passwd.db
  command: "{{ postfix_postmap }} {{ postfix_sasl_passwd }}"
- name: build aliases.db
  command: "{{ postfix_newaliases }}"
